_target_: src.datamodules.superres_datamodule.SuperResDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 32
train_val_test_split: [455, 30, 50]
num_workers: 0
pin_memory: False
shape: [128, 128]
